///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;
using DHSAutomation.Common;
using WinForms = System.Windows.Forms;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using DHSAutomation.Keywords;
namespace DHSAutomation.Keywords.LaunchOtherSW
{
    public partial class CheckWarrantyNoRegistedText
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
            
            repo.DHSForm.Warranty.Click();
        }
        
        public void Blinking()
        {
        	Delay.Seconds(4);
        	DialogResult rs = DialogUtils.DialogConfirm("Did warrant text box blinking 2 times?");
        	if (rs==DialogResult.Yes) Report.Success("The registration section is displayed 2 times");
        	else Report.Failure("The registration section is not displayed 2 times");
        }
        
        public void RegisterText()
        {
        	if (repo.DHSMainWindow.RegisTextInfo.Exists(10000))
        	{
        		if (repo.DHSMainWindow.RegisText.Caption.Contains("Please take a moment to register your system.")) Report.Success("Registration status success");
        		else Report.Failure("Registration status failure");
        		return;
        	}
        	Report.Failure("Registration status failure");
        }
        
    }
}