///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;
using WinForms = System.Windows.Forms;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace DHSAutomation.Keywords.LaunchOtherSW
{
    public partial class DisableDellUpdate
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        public void Diable ()
        {
        	Delay.Seconds(2);
        	repo.Taskbar.Popup.Click();
        	Delay.Seconds(2);
        	repo.Explorer.DellUpdate.Click(MouseButtons.Right);
        	Delay.Seconds(1);
        	

        	repo.DellUpdateMenu.EnableAutoCheckInfo.WaitForExists(120000);
        	if (repo.DellUpdateMenu.EnableAutoCheck.Enabled) repo.DellUpdateMenu.EnableAutoCheck.Click();
        	Delay.Seconds(4);
        }

    }
}