///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using WinForms = System.Windows.Forms;

namespace DHSAutomation.Keywords.LaunchOtherSW
{
    public partial class EnableDellUpdate
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        public void Enable ()
        {
        	if (repo.DHSForm.DellUpdateText1Info.Exists(20000)&&repo.DHSForm.ENABLEInfo.Exists(20000))
        	{
        		Report.Success("Dell Update disable text and button displayed correctly");
        		
        		repo.DHSForm.ENABLE.Click();
        		
        		Delay.Seconds(5);
        		
        		Delay.Seconds(2);
		    	repo.Taskbar.Popup.Click();
		    	Delay.Seconds(2);
		    	repo.Explorer.DellUpdate.Click(MouseButtons.Right);
		    	Delay.Seconds(5);
		    	if (repo.DellUpdateMenu.EnableAutoCheck.Enabled) Report.Success("Dell Update enable successfull");
		    	else Report.Failure("Dell Update enable failure");
		    	
        	}else Report.Failure("Dell Update disable text and button displayed failure");
        }

    }
}