///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;
using DHSAutomation.Common;
using WinForms = System.Windows.Forms;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace DHSAutomation.Keywords.LaunchOtherSW
{
    public partial class FeedbackCheck
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        public void Feedback ()
        {
        	repo.DHSMainWindow.Feedback.Click();
        	Delay.Seconds(5);
        	if (repo.DellInAppStudy.SelfInfo.Exists(20000))
        	{
        		DialogResult rs = DialogUtils.DialogConfirm("Please check there is no garbage/cutoff on the page \n Please check if the page is readable and cannot be zoom in/out");
        		if (rs== DialogResult.Yes) Report.Success("Feedback page is displayed correctly");
        		else Report.Failure("Feedback page is displayed incorrectly");
        	}
        	
        	Delay.Seconds(5);        	
        	
        }

    }
}