///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace DHSAutomation.Keywords.LaunchOtherSW
{
	public partial class RegistingDellProduct
	{
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			// Your recording specific initialization code goes here.
			
			repo.DHSForm.Warranty.Click();
			Delay.Seconds(3);
		}
		
		public void OpenRegisform ()
		{
			Report.Log(ReportLevel.Info, "Click Register Button!");
			if (repo.DHSMainWindow.RegisterBtnInfo.Exists(20000)) repo.DHSMainWindow.RegisterBtn.Click();
			else return;
			Delay.Seconds(7);
		}
		
		public void CloseRegisform ()
		{
			Delay.Seconds(10);
			repo.ProductRegistration.Self.As<Ranorex.Form>().Close();
		}
		
		public void InputCity ()
		{
			Delay.Seconds(1);
			repo.ProductRegistration2.Text.TextValue = "Hanoi";
			Delay.Seconds(1);
		}

		public void SetInfoRegister()
		{
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Click item 'First Name'");
			repo.ProductRegistration.SvFiledsPart.HintText.Click("17;2", 300);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Input 'First Name'");
			repo.ProductRegistration.SvFiledsPart.Text.PressKeys("Nguyen");
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Click item 'Last Name'");
			repo.ProductRegistration.SvFiledsPart.HintText1.Click("19;1", 300);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Input 'Last Name'");
			repo.ProductRegistration.SvFiledsPart.Text1.PressKeys("Thanh Hai");
			
			Report.Log(ReportLevel.Info, "Keyboard", "Input 'Email'");
			repo.ProductRegistration.SvFiledsPart.Text2.PressKeys("dell.france11@gmail.com");
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Click item 'Address'");
			repo.ProductRegistration.SvFiledsPart.HintText3.Click("231;3", 300);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Input 'Address'");
			repo.ProductRegistration.SvFiledsPart.Text3.PressKeys("43 TDT");
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Click item 'Zip Code'");
			repo.ProductRegistration.SvFiledsPart.HintText4.Click("42;6", 300);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Input 'Zip Code'");
			repo.ProductRegistration.SvFiledsPart.Text4.PressKeys("10000");
			Delay.Milliseconds(200);
						
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Click item 'City'");
			repo.ProductRegistration.SvFiledsPart.HintText5.Click("112;0", 300);
			Delay.Milliseconds(200);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Input 'City'");
//			repo.ProductRegistration.SvFiledsPart.Text5.PressKeys("Ha Noi ");
			repo.ProductRegistration.SvFiledsPart.Text5.TextValue ="Hanoi";
			Delay.Seconds(2);

			Report.Log(ReportLevel.Info, "Mouse", "Mouse Click item 'State'");
			repo.ProductRegistration.SvFiledsPart.ComboBox1.Click("64;13", 300);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'A'.");
			Keyboard.Press("A");
			
			Delay.Seconds(1);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{ENTER}'.");
			Keyboard.Press("{ENTER}");
			
			Delay.Seconds(2);
			
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Click item 'HWYUYD'");
			repo.ProductRegistration.SvFiledsPart.ComboBox.Click("228;11", 300);
			
			Report.Log(ReportLevel.Info, "Delay", "Waiting for 400ms.");
			Delay.Duration(400, false);
			
			
			Report.Log(ReportLevel.Info, "Keyboard", "Select 'Personal'");
			Keyboard.Press("P");
			Delay.Seconds(1);
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{ENTER}'.");
			Keyboard.Press("{ENTER}");
			
			Report.Log(ReportLevel.Info, "Delay", "Waiting for 400ms.");
			Delay.Duration(400, false);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Click item 'Register' button");
			repo.ProductRegistration.BtnRegister.Click("190;15", 300);
		}

	}
}