///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace DHSAutomation.Keywords.SplashScreen
{
    public partial class CheckExpressAndMoveCursor
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void ValidateExpressServiceCodeTooltip()
        {
        	if(isConfirmManualSteps.Equals("True")){
				string msg = "Please check if the information of Express Service Code should be showed up when hold tooltip (Yes/No)";
				string msgResult = "The information of Express Service Code should be showed up!";
				WinForms.DialogResult result =  WinForms.MessageBox.Show(new WinForms.Form{TopMost = true},
				                                                         msg, "Confirm Step",
				                                                         WinForms.MessageBoxButtons.YesNo,
				                                                         WinForms.MessageBoxIcon.Question,
				                                                         WinForms.MessageBoxDefaultButton.Button1);
				Report.Log(result == WinForms.DialogResult.Yes?ReportLevel.Success:ReportLevel.Failure, msgResult);
				
			}
        }

        public void CheckServiceCodeInfo()
        {
        	string serviceCode = repo.DHSMainWindow.ServiceCode.GetAttributeValue<String>("Text");
        	if(serviceCode.Contains(varServiceCode)){
        		Report.Log(ReportLevel.Success, "Service Code on DHS same as Service Code of device test!");
        	   }else{
        	   	Report.Log(ReportLevel.Failure, "Service Code on DHS same as Service Code of device test!");
        	   }
        }

        public void Mouse_Move_ServiceCodeTooltip()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Service Code Tool tip'.");
            repo.DHSMainWindow.ServiceCodeTooltip.MoveTo();
        }

    }
}