///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace DHSAutomation.Keywords.SplashScreen
{
    public partial class CheckDisplayedSUTModel
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void CheckPlatformName()
        {
        	string LOB = repo.DHSMainWindow.PlatformName.GetAttributeValue<String>("Text");
        	if(LOB.Contains(varPlatformName)){
        		Report.Log(ReportLevel.Success, "Platform Name on DHS same as device test!");
        	   }else{
        	   	Report.Log(ReportLevel.Failure, "Platform Name on DHS same as device test!");
        	   }
        }

    }
}