///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace DHSAutomation.Keywords.SplashScreen
{
    public partial class DisconnectInternetAndRepeatOneToFive
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
        	Keywords.General.CloseDHS.Start();
        	Keywords.Network.OpenNetworkConnectionPanel.Start();
        	Keywords.Network.DisableNetwork.Start();
        	Keywords.Network.CloseNetworkConnectionPanel.Start();
        	Keywords.TelemetryEventsCheckFromDAWS.OpenDellHelpAndSupport.Start();
        	Keywords.Validation.CheckSplashScreen.Start();
        	Keywords.Validation.CheckImageBeautyShot.Start();
        	Keywords.SplashScreen.CheckDisplayedSUTModel.Start();
        	Keywords.SplashScreen.CheckServiceTagAndMoveCursor.Start();
        	Keywords.General.CloseDHS.Start();
        	
        }

    }
}