///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DHSAutomation.Keywords.Validation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckDHSInstalled recording.
    /// </summary>
    [TestModule("48a87b12-4d5c-4498-a61e-6a0de05caf50", ModuleType.Recording, 1)]
    public partial class CheckDHSInstalled : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DHSAutomation.DHSAutomationRepository repository.
        /// </summary>
        public static DHSAutomation.DHSAutomationRepository repo = DHSAutomation.DHSAutomationRepository.Instance;

        static CheckDHSInstalled instance = new CheckDHSInstalled();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckDHSInstalled()
        {
            isConfirmManualSteps = "True";
            varAppVersion = "2.2.26";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckDHSInstalled Instance
        {
            get { return instance; }
        }

#region Variables

        string _isConfirmManualSteps;

        /// <summary>
        /// Gets or sets the value of variable isConfirmManualSteps.
        /// </summary>
        [TestVariable("708e14ad-0dab-4f73-8ed6-80dc63378b6b")]
        public string isConfirmManualSteps
        {
            get { return _isConfirmManualSteps; }
            set { _isConfirmManualSteps = value; }
        }

        string _varAppVersion;

        /// <summary>
        /// Gets or sets the value of variable varAppVersion.
        /// </summary>
        [TestVariable("31795704-71ee-4e2d-aee5-7feec41cb082")]
        public string varAppVersion
        {
            get { return _varAppVersion; }
            set { _varAppVersion = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            ConfirmInstallationCriteria();
            Delay.Milliseconds(0);
            
            CheckProgramAndFeatureInfo();
            Delay.Milliseconds(0);
            
            CheckServiceIsRunningInTaskManager();
            Delay.Milliseconds(0);
            
            CheckServiceDetail();
            Delay.Milliseconds(0);
            
            CheckRegistryKeyExist();
            Delay.Milliseconds(0);
            
            CheckDigitalSignature();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
