///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace DHSAutomation.Keywords.Validation
{
	public partial class CheckSplashScreen
	{
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			Delay.Seconds(5);
		}

		public void ValidationSplashScreen()
		{
			if(isConfirmManualSteps.Equals("True")){
				string msg = "Please check the infomation below: \n\n"+
					"1. The Splash screen showed up \n"+
					"2. Splash screen contains: \n"+
					  "- Icon picture displayed \n"+
					  "- Text: Dell Help & Support \n"+
					  "- DHS version: "+versionApp+"\n\n"+
					"Are their information correctly (Yes/No)?";
				//string msgResult = "The Splash screen should be showed up!";
				WinForms.DialogResult result =  WinForms.MessageBox.Show(new WinForms.Form{TopMost = true},
				                                                         msg, "Confirm Step",
				                                                         WinForms.MessageBoxButtons.YesNo,
				                                                         WinForms.MessageBoxIcon.Question,
				                                                         WinForms.MessageBoxDefaultButton.Button1);
				//Report.Log(result == WinForms.DialogResult.Yes?ReportLevel.Success:ReportLevel.Failure, msgResult);
				if(result == WinForms.DialogResult.Yes){
					Report.Success("The Splash screen has been showed up.");
					Report.Success("Icon picture displayed.");
					Report.Success("Text: Dell Help & Support is displayed.");
					Report.Success("DHS version: "+versionApp+" is displayed.");
				}else{
					Report.Failure("The Splash screen does not show up.");
				}
			}
		}

	}
}