///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using DHSAutomation.Common;

namespace DHSAutomation.Keywords.Validation
{
    public partial class CheckImageBeautyShot
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void ValidationImageBeautyShot()
        {
        	if(isConfirmManualSteps.Equals("True")){
				string msg = "Please check the infomation below: \n\n"+
					"1. The generic beauty shot should be displayed align with user's form factor and LOB. \n" +
					"2. The picture display on DHS same as the picture from "+ @"C:\ProgramData\Dell\Dell Help & Support\beautyshot.png"+"\n\n"+
					"Are their information correctly? (Yes/No)";
				string msgResult = "The generic beauty shot should be displayed correctly!";
				WinForms.DialogResult result =  WinForms.MessageBox.Show(new WinForms.Form{TopMost = true},
				                                                msg, "Confirm Step",
				                                                WinForms.MessageBoxButtons.YesNo,
				                                                WinForms.MessageBoxIcon.Question,
				                                                WinForms.MessageBoxDefaultButton.Button1);
				//Report.Log(result == WinForms.DialogResult.Yes?ReportLevel.Success:ReportLevel.Failure, msgResult);
				if(result == WinForms.DialogResult.Yes){
					Report.Success("The generic beauty shot is displayed correctly.");
				}else{
					Report.Success("The generic beauty shot is not displayed correctly.");
				}
			}
        }

        public void OpenImageFile()
        {
        	Utils.OpenFile(@"C:\ProgramData\Dell\Dell Help & Support\beautyshot.png");
        }

        public void MergedUserCodeMethod()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Middle Click Image beauty shot item.");
            repo.Photos.ImageBeautyshot.Click(System.Windows.Forms.MouseButtons.Middle);
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Alt+F4' Press.");
            Keyboard.Press(System.Windows.Forms.Keys.F4 | System.Windows.Forms.Keys.Alt, 62, Keyboard.DefaultKeyPressTime, 1, true);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move Click Image beauty shot.");
            repo.DHSFolder.ImageFile.MoveTo();
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Close'.");
            repo.DHSFolder.Close.Click("19;15", 200);
        }

    }
}