///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

using DHSAutomation.Objects;

namespace DHSAutomation.Keywords.Validation
{
	public partial class CheckSNPPage
	{
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			// Your recording specific initialization code goes here.
		}

		public void CheckSNP()
		{
			Text findAccessoriesText = repo.DHSMainWindow.FindAccessories.FindSingle(".");
			findAccessoriesText.Click();
			Delay.Milliseconds(5000);
			
//			if IE run the first time, check "use recommend ..." and click ok
			firstRun fr = new firstRun();
			fr.checkIEForm();
			
			try{
				repo.IE.TitleBarInfo.WaitForExists(10000);
				try{
					repo.IESetupPopop.SetupIETitleInfo.WaitForExists(10000);
					repo.IESetupPopop.RadioButtonUseRecommended.Click();
					repo.IESetupPopop.ButtonOK.Click();
				}
				catch(RanorexException ex){
				}
				
				Report.Log(ReportLevel.Success, "IE is opened SNP Page");
				
				// check region
				Keyboard.Press("{End}");
				ATag country = repo.DellSupport.ProductSupportDellUS.CountryName.FindSingle<ATag>(".");
				country.MoveTo();
				Delay.Milliseconds(2000);
				string countryName = country.InnerText.Trim();
				string geoCountryName = GetCurrentGEOLocationCountry().Trim();
				Report.Log((countryName == geoCountryName)?ReportLevel.Success:ReportLevel.Failure, "Check if country found on Dell SNP {" + countryName + "} same with current GEO country {"+ geoCountryName +"}");
				repo.IE.Close.Click();
			}
			catch(RanorexException ex){
				Report.Log(ReportLevel.Failure, "SNP Page was not opened");
			}
		}

		public static string GetCurrentGEOLocationCountry(){
			Host.Local.OpenBrowser("http://ipaddress.com/", "IE", "", false, true, false, false, false);
			repo.WhatIsMyIPAddress.TdTagCountryInfo.WaitForExists(10000);
			repo.WhatIsMyIPAddress.TdTagCountry.MoveTo();
			Delay.Milliseconds(2000);
			string coutryName = repo.WhatIsMyIPAddress.TdTagCountry.InnerText;
			Keyboard.Press("{LControlKey down}{Wkey}{LControlKey up}");
			return coutryName;
		}
	}
}