///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DHSAutomation.Keywords.Validation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckFunctionFeedBackPage recording.
    /// </summary>
    [TestModule("ab5103c1-9f8b-4345-86e3-bab3a8428895", ModuleType.Recording, 1)]
    public partial class CheckFunctionFeedBackPage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DHSAutomation.DHSAutomationRepository repository.
        /// </summary>
        public static DHSAutomation.DHSAutomationRepository repo = DHSAutomation.DHSAutomationRepository.Instance;

        static CheckFunctionFeedBackPage instance = new CheckFunctionFeedBackPage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckFunctionFeedBackPage()
        {
            likelyFeedBack = "0";
            satisfiedFeedBack = "0";
            commentFeedBack = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckFunctionFeedBackPage Instance
        {
            get { return instance; }
        }

#region Variables

        string _commentFeedBack;

        /// <summary>
        /// Gets or sets the value of variable commentFeedBack.
        /// </summary>
        [TestVariable("f376dbf4-19ae-4225-9241-3871a66559ce")]
        public string commentFeedBack
        {
            get { return _commentFeedBack; }
            set { _commentFeedBack = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable satisfiedFeedBack.
        /// </summary>
        [TestVariable("6accc76c-3181-4e62-8445-e6058d03da56")]
        public string satisfiedFeedBack
        {
            get { return repo.satisfiedFeedBack; }
            set { repo.satisfiedFeedBack = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable likelyFeedBack.
        /// </summary>
        [TestVariable("62aee24e-80e0-4cc6-befc-6513fe9647cd")]
        public string likelyFeedBack
        {
            get { return repo.likelyFeedBack; }
            set { repo.likelyFeedBack = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varDHSAppName.
        /// </summary>
        [TestVariable("ee1811b5-a80d-417d-94eb-7a6ed899b6f4")]
        public string varDHSAppName
        {
            get { return repo.varDHSAppName; }
            set { repo.varDHSAppName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Mouse_Click_SatisfiedNum();
            Delay.Milliseconds(0);
            
            Mouse_Click_LikelyNum();
            Delay.Milliseconds(0);
            
            Mouse_Click_Type();
            Delay.Milliseconds(0);
            
            Mouse_Enter_Comment();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FeedBack.SendMyFeeback' at 73;15.", repo.FeedBack.SendMyFeebackInfo, new RecordItemIndex(4));
            repo.FeedBack.SendMyFeeback.Click("73;15", 200);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FeedBack.Finish' at 58;11.", repo.FeedBack.FinishInfo, new RecordItemIndex(5));
            repo.FeedBack.Finish.Click("58;11", 200);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DHSForm.FeedbackTxt' at Center.", repo.DHSForm.FeedbackTxtInfo, new RecordItemIndex(7));
            repo.DHSForm.FeedbackTxt.Click(200);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'DHSForm.BackImage'.", repo.DHSForm.BackImageInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.DHSForm.BackImageInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DHSForm.BackImage' at Center.", repo.DHSForm.BackImageInfo, new RecordItemIndex(9));
            repo.DHSForm.BackImage.Click(200);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
