///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace DHSAutomation.Keywords.Validation
{
    public partial class CheckFunctionFeedBackPage
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Mouse_Click_SatisfiedNum()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse choose number satisfied Feed Back: ", repo.FeedBack.SatisfiedNumInfo);
            repo.FeedBack.SatisfiedNum.Click("10;7");
            Delay.Milliseconds(200);
        }

        public void Mouse_Click_LikelyNum()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse choose number likely Feed Back ", repo.FeedBack.LikelyNumInfo);
            repo.FeedBack.LikelyNum.Click("10;7");
            Delay.Milliseconds(200);
        }

        public void Mouse_Click_Type()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse choose type of Feed Back ", repo.FeedBack.TypeInfo);
            repo.FeedBack.Type.Click();
            Delay.Milliseconds(200);
        }

        public void Mouse_Enter_Comment()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FeedBack.EnterAComment' at 20;13.", repo.FeedBack.EnterACommentInfo);
            repo.FeedBack.EnterAComment.Click("20;13");
            Delay.Milliseconds(200);
             
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey}Dell DHS{LShiftKey down}'.");
            Keyboard.Press("{LShiftKey}"+commentFeedBack+"{LShiftKey down}");
        }

    }
}