///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace DHSAutomation.Keywords.Network
{
	public partial class LoadNetworkConnectionStatus
	{
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			// Your recording specific initialization code goes here.
		}

		public void GetNetworkConnectionStatus()
		{
			// get connecting network, get & store the first one
			try{
				repo.Network.NetworkConnectionPanel.NetworkConnectedItemsInfo.WaitForExists(new Duration(3000));
				
				IList<ListItem> connectionItems = repo.Network.NetworkConnectionPanel.NetworkConnectedItems.Find<ListItem>(".");
				ListItem connectionItem = connectionItems[0];
				TestSuite.Current.Parameters["networkConnectionStatus"] = "Connected";
				// get connection name
				string connectionName = connectionItem.Text;
				TestSuite.Current.Parameters["networkConnectionName"] = connectionName;
				
			}
			catch(RanorexException ex){
				TestSuite.Current.Parameters["networkConnectionStatus"] = "Disconnected";
				System.Console.WriteLine(ex.ToString());
			}
		}

	}
}