///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DHSAutomation.Keywords.QuickStartGuide
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckQSGOnline recording.
    /// </summary>
    [TestModule("c047bf18-00bf-4e7c-a87c-c28066fa410b", ModuleType.Recording, 1)]
    public partial class CheckQSGOnline : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DHSAutomation.DHSAutomationRepository repository.
        /// </summary>
        public static DHSAutomation.DHSAutomationRepository repo = DHSAutomation.DHSAutomationRepository.Instance;

        static CheckQSGOnline instance = new CheckQSGOnline();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckQSGOnline()
        {
            varPlatformName = "Inspiron 3558";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckQSGOnline Instance
        {
            get { return instance; }
        }

#region Variables

        string _varPlatformName;

        /// <summary>
        /// Gets or sets the value of variable varPlatformName.
        /// </summary>
        [TestVariable("a654ac36-a000-4fda-bd20-6873b03b4f21")]
        public string varPlatformName
        {
            get { return _varPlatformName; }
            set { _varPlatformName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varDHSAppName.
        /// </summary>
        [TestVariable("ee1811b5-a80d-417d-94eb-7a6ed899b6f4")]
        public string varDHSAppName
        {
            get { return repo.varDHSAppName; }
            set { repo.varDHSAppName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            ClickManualsTab();
            Delay.Milliseconds(0);
            
            ClickQuickStartGuide();
            Delay.Milliseconds(0);
            
            CheckPDFOpen();
            Delay.Milliseconds(0);
            
            CheckPDFLanguage();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Wkey}{LControlKey up}'.", new RecordItemIndex(4));
            Keyboard.Press("{LControlKey down}{Wkey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            OpenDellAgentLog();
            Delay.Milliseconds(0);
            
            CheckQSGWebServiceURL();
            Delay.Milliseconds(0);
            
            CheckQSGDownloadURL();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DellAgentMDLC00LogNotepad.Close' at 23;14.", repo.DellAgentMDLC00LogNotepad.CloseInfo, new RecordItemIndex(8));
            repo.DellAgentMDLC00LogNotepad.Close.Click("23;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.Close' at 29;14.", repo.Explorer.CloseInfo, new RecordItemIndex(9));
            repo.Explorer.Close.Click("29;14");
            Delay.Milliseconds(200);
            
            ClickViewAllManuals();
            Delay.Milliseconds(0);
            
            CheckDellSupportOpenIE();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
