///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;
using WinForms = System.Windows.Forms;
using System.IO;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace DHSAutomation.Keywords.General
{
	public partial class InstallDHS
	{
		//public static DHSAutomation.DHSAutomationRepository repo = DHSAutomation.DHSAutomationRepository.Instance;
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			OpenInstaller();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dell Help & Support' label.");
            repo.InstallShieldWizard.Text1302.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click button 'Install'.");
            repo.InstallShieldWizard.ButtonInstall.Click();
            Delay.Milliseconds(200);
            repo.InstallShieldWizard.Text711Info.WaitForExists(120000);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Installed information'.");
            repo.InstallShieldWizard.Text711.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click button 'Finish'.");
            try{
            repo.InstallShieldWizard.Finish.Click();
            Report.Success("DHS is installed.");
            }catch(Exception){
            	Report.Failure("DHS install not successfully.");
            }
            Delay.Milliseconds(200);
			// Your recording specific initialization code goes here.
		}

		public void OpenInstaller()
		{
			// press Window r open file explorer
			string installer = Directory.GetCurrentDirectory() + @"\Resources\DellHelp&Support_v"+ varAppVersion +".exe";
			System.Diagnostics.Process.Start(installer);
		}
	}
}