///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using DHSAutomation.Common;
using DHSAutomation.Objects;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using WinForms = System.Windows.Forms;

namespace DHSAutomation.Keywords.General
{
	public partial class OpenDHS
	{
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			// Your recording specific initialization code goes here.
		}
		
		public void Enter()
		{
			CultureInfo ci = Utils.GetOSLanguage();
			
			if (ci.Name.ToLower().Contains("pt"))
			{
				Keyboard.Press("{DOWN}");
				Keyboard.Press("{ENTER}");
			}else Keyboard.Press("{ENTER}");
		}
		
		
		public void OpenApp()
		{
//			repo.Taskbar.Start.Click();
//			Delay.Milliseconds(200);
//			
//			repo.Start.ContainerHash.Click();
//			Delay.Milliseconds(200);
//			
//			repo.Start.TextD.Click();
//			Delay.Milliseconds(200);
			
			try{
//				repo.Start.AppsList.Click(new Location(AppsList_Screenshot1, "4;4", AppsList_Screenshot1_Options));
//				Delay.Milliseconds(200);
//				
				repo.Start.AppsList.Click(new Location(AppsList_Screenshot2, "12;15", AppsList_Screenshot2_Options));
				Delay.Milliseconds(200);
				
				Report.Log(ReportLevel.Success, "DHS Icon found on All App Start Menu");
				
//				Delay.Seconds(5);
				if (repo.DHSForm.SelfInfo.Exists(30000)) Report.Success("DHS Main UI show up success");
				else Report.Failure("DHS Main UI show up failure");
				
				
			}
			catch(RanorexException){
				Report.Log(ReportLevel.Failure, "DHS Icon NOT found on All App Start Menu");
			}
			
			
//			if DHS is THeadTag 1st time running, "Warranty" panel will be enabled and need to be closed
			firstRun fr = new firstRun();
			Delay.Milliseconds(5000);
			fr.checkDHSFirstRun();
		}
		
		#region Image Feature Data
		CompressedImage AppsList_Screenshot1
		{ get { return repo.Start.AppsListInfo.GetScreenshot1(new Rectangle(27, 51, 8, 8)); } }

		Imaging.FindOptions AppsList_Screenshot1_Options
		{ get { return Imaging.FindOptions.Default; } }

		CompressedImage AppsList_Screenshot2
		{ get { return repo.Start.AppsListInfo.GetScreenshot2(new Rectangle(31, 81, 18, 19)); } }

		Imaging.FindOptions AppsList_Screenshot2_Options
		{ get { return Imaging.FindOptions.Default; } }
		#endregion
	}
}