///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace DHSAutomation.Keywords.General
{
	public partial class UninstallDHS
	{
		/// <summary>
		/// This method gets called right after the recording has been started.
		/// It can be used to execute recording specific initialization code.
		/// </summary>
		private void Init()
		{
			// Your recording specific initialization code goes here.
		}

		public void chooseToUninstall()
		{
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ControlPanel.ProgramsAndFeatures.RowDHS' at 88;14.", repo.ControlPanel.ProgramsAndFeatures.RowDHSInfo);
			IList<Cell> cellList = repo.ControlPanel.ProgramsAndFeatures.RowDHS.Find<Ranorex.Cell>("./cell");
			
			foreach(Cell cellVer in cellList){
				
				String itemName = cellVer.GetAttributeValue<String>("Text");
				if(itemName.Contains(varAppVersion)){
					cellVer.Click();
					break;
				}
				
			}
		}
		
		public void DelayForFinish ()
		{
			//        	repo.UninstallComplete.FinishInfo.WaitForExists(180000);
			while(true){
				if(repo.UninstallComplete.FinishInfo.Exists(3000)){
					Report.Log(ReportLevel.Info, "Finish button exists!");
					Report.Log(ReportLevel.Info, "Mouse", "Mouse click Finish button!");
					repo.UninstallComplete.Finish.Click(300);
					break;
				}else{
					Delay.Seconds(5);
				}
			}
			
		}

       
        public void MouseClickProgramAndFeature()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Click item 'Programs'");
            repo.ControlPanel.CPanel.Programs.Click(300);

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Click item 'Programs And Features'");
            repo.ControlPanel.Programs.ProgramsAndFeatures.Click(300);
        }

        public void MouseClickUninstallButton()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Click 'Uninstall' button");
            repo.ControlPanel.ProgramsAndFeatures.ButtonUninstall.Click(300);
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click 'Yes' button");
            repo.DellHelpSupportInstallShieldWizar.ButtonYes.Click(Location.CenterLeft, 300);
        }

        public void Mouse_Click_Close()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Click 'Close' button");
            repo.ControlPanel.ProgramsAndFeatures.Close.Click(300);
        }

	}
}