///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DHSAutomation.Keywords.General
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UninstallDHS recording.
    /// </summary>
    [TestModule("59c268c4-bf6b-403d-bf55-25e061c23761", ModuleType.Recording, 1)]
    public partial class UninstallDHS : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DHSAutomation.DHSAutomationRepository repository.
        /// </summary>
        public static DHSAutomation.DHSAutomationRepository repo = DHSAutomation.DHSAutomationRepository.Instance;

        static UninstallDHS instance = new UninstallDHS();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UninstallDHS()
        {
            varAppVersion = "2.2.26.0";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UninstallDHS Instance
        {
            get { return instance; }
        }

#region Variables

        string _varAppVersion;

        /// <summary>
        /// Gets or sets the value of variable varAppVersion.
        /// </summary>
        [TestVariable("275fe6ac-323a-4f6f-9d1c-dbdc8f800bbe")]
        public string varAppVersion
        {
            get { return _varAppVersion; }
            set { _varAppVersion = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LWin down}r{LWin up}'.", new RecordItemIndex(0));
            Keyboard.Press("{LWin down}r{LWin up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'control{Return}'.", new RecordItemIndex(2));
            Keyboard.Press("control{Return}");
            Delay.Milliseconds(0);
            
            MouseClickProgramAndFeature();
            Delay.Milliseconds(0);
            
            chooseToUninstall();
            Delay.Milliseconds(0);
            
            MouseClickUninstallButton();
            Delay.Milliseconds(0);
            
            DelayForFinish();
            Delay.Milliseconds(0);
            
            Mouse_Click_Close();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
