///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using DHSAutomation.Common;
using WinForms = System.Windows.Forms;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace DHSAutomation.Keywords.ContentSelfupdate
{
    public partial class AddConfig
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        public void CopyConfig ()
        {
        	Delay.Seconds(20);
        	if (File.Exists(@".\Resources\DHSSrv.exe.config")) File.Copy(@".\Resources\DHSSrv.exe.config",@"C:\ProgramData\Dell\Dell Help & Support\DHSSrv.exe.config");
        	Utils.ExecuteCommand("stop \"Dell Help & Support\"","net");
			Delay.Seconds(5);
        }
        
        public void RestartService()
        {
        	Utils.ExecuteCommand("start \"Dell Help & Support\"","net");
        }
        
        

    }
}