///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;
using DHSAutomation.Common;
using WinForms = System.Windows.Forms;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace DHSAutomation.Keywords.ContentSelfupdate
{
    public partial class CheckUpdatedContent
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        public void ClickImageButton ()
        {
        	Delay.Seconds(5);
			if (repo.DHSMainWindow.ClosePanelImageInfo.Exists(10)) repo.DHSMainWindow.ClosePanelImage.Click();
			Delay.Seconds(2);
			
        	repo.DHS_HaiNT21_Form.CircleButton.Click();
        	
        	DialogResult rs = DialogUtils.DialogConfirm("Did image is updated (Test image have red scrible)");
        	if (rs== DialogResult.Yes) Report.Success("New content is updated successfully");
        	else Report.Failure("New content is not updated");
        }

    }
}