///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Xml.Linq;
using System.Xml.XPath;

using DHSAutomation.Common;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using WinForms = System.Windows.Forms;

namespace DHSAutomation.Keywords
{
    public partial class ChangeLanguage
    {
    	
    	string[] languages = new string[]{"de-DE", "zh-CN", "ja-JP", "ko-KR", "pt-BR", "fr-FR", "es-ES", "en-US"};
    	
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
        	foreach (var lang in languages) {
        		if (!File.Exists("Resources/" + lang + ".lg")) File.Create("Resources/" + lang + ".lg");
        	}
        }
        
        public void ClickLastChild ()
        {
        	IList<Ranorex.Row> listRow = repo.Link_to_last_language.Self.As<Ranorex.Table>().Rows;
        	
        	listRow[listRow.Count-1].DoubleClick();
        	Delay.Seconds(2);
        }
        


        public void SignOut()
        {
        	CultureInfo ci = Utils.GetOSLanguage();
        	if (!File.Exists("Resources/" + ci.Name + ".out")) {
        		File.Create("Resources/" + ci.Name + ".out");
        	} else return;
        	
//        	Utils.DisableAboveModule();
        	
        	Utils.RunAtStartupUsingBatFile();
        	Utils.SignOut();
        	Delay.Seconds(10);
        }
    }
}