///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace DHSAutomation.Keywords
{
    public partial class DoSearch
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContentHost'.");
            repo.DHSMainWindow.PARTContentHost.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '"+varKeyword.ToString()+"' with focus on 'Search'.");
            repo.DHSMainWindow.TextSearch.PressKeys(varKeyword);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Results'.");
            try{
            repo.DellHelpSupport.NoResultsFound.Click();
            Report.Success("No search result found.");
            }catch{
            	Report.Failure("Search result found.");
            }
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'Search'.");
            repo.DHSMainWindow.TextSearch.PressKeys("{Return}");
            Delay.Milliseconds(0);
        }

    }
}