///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;

using DHSAutomation.Common;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using WinForms = System.Windows.Forms;

namespace DHSAutomation.Keywords
{
    public partial class SignOutNoneDisableAbove
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void SignOut()
        {
        	CultureInfo ci = Utils.GetOSLanguage();
        	if (!File.Exists("Resources/" + ci.Name + ".out")) {
        		File.Create("Resources/" + ci.Name + ".out");
        	} else 
        	{
        		
        		Utils.DisableAboveModule(this);
        		return;
        		
        	}
        	
        	
        	Utils.RunAtStartupUsingBatFile();
        	Utils.SignOut();
        	Delay.Seconds(10);
        }

    }
}